name = "cdndash"
compatibility_date = "2026-10-01"
pages_build_output_dir = "./dist"

[vars]
TARGET_OWNER = "MadisonWirtanen"
TARGET_REPO = "cdn"
TARGET_BRANCH = "master"
PUBLIC_BASE_URL = "https://cdn.003153.xyz"
DEFAULT_UPLOAD_DIR = "image"
MAX_UPLOAD_MB = "25"
ALLOW_DELETE = "true"
ALLOW_OVERWRITE = "true"
ALLOW_RENAME = "true"
PROTECTED_PATHS = "index.html,404.html"
ALLOWED_HOSTS = "cdndash.003153.xyz"
